### ISSUE TITLE
2 versions of CODA licence

### ISSUE THREAD

**Issue by cfsnook** [eventB-Soton/CODA_Utils#4]
There are 2 different versions of the CODA software user agreement in ac.soton.coda.licence
1) licence.html  (I think this is the correct one) is shorter and only refers to EPL. This is used in the about, branding etc.

2) feature.txt  has a text field 'CODALicence' which is a longer (older) version that refers specifically to the US Governement. This version is shown when you install CODA.

Version 2 is also contained in the documentation plugins (2 places in ac.soton.coda.doc and once in ac.soton.coda.simulator2.doc) but this does not appear to be shown in the Rodin help system. Possibly because we have not re-issued the documentation?

![image](https://user-images.githubusercontent.com/1729886/52335476-6683fe80-29fa-11e9-81db-789a5801e11c.png)

**Comment by tshoang** [comment]
@cfsnook We haven't regenerated the documentation as the scripts are broken when the repo was split.
